### ISSUE TITLE
Download video, mp3 frpm REST API only

### ISSUE THREAD

**Issue by mogupta** [Totonyus/ydl_api_ng#24]
Hi Great work!. I am able to download videos & mp3 from youtube but not sure how to download it from the API ? the docker container will be on a remote server.

**Comment by Totonyus** [comment]
Hi !

The documentation is based on the default `params.ini` file provided when you launch the container the first time. Here some examples in the documentation : https://github.com/Totonyus/ydl_api_ng?tab=readme-ov-file#downloads

You just have to replace `localhost` with the ip of the machine where the container runs and the port (`5011`) by the port you forwarded to the container's `80`

Same if you use the userscript provided, you have to configure the api's url in the javascript : https://github.com/Totonyus/ydl_api_ng/blob/94ddbeef21d173aa615c8fd6ac1827e61dc539eb/params/userscript.js#L14
