### ISSUE TITLE
iOS Shortcut?

### ISSUE THREAD

**Issue by werid** [Totonyus/ydl_api_ng#4]
hi, the old `ydl_api` had an iOS shortcut, and you mentioned in your reddit announcement that you might have one for this too, so I was wondering if that's something that's coming soon? It's the final piece of the puzzle for me, as I often want to send URL's from my phone to this tool.

**Comment by Totonyus** [comment]
Hi !

Even if the old shortcut somehow still works I reworked it : https://www.icloud.com/shortcuts/deb4fea950ee436daf9a1f668a55add4

Note you'll need to update the application to the last commit.

**Comment by werid** [comment]
Thanks, works great!
