### ISSUE TITLE
Compatible with ARM64?

### ISSUE THREAD

**Issue by vasanthtt** [Totonyus/ydl_api_ng#8]
I deployed docker on host Debian/ARM64 but it didn't work.  Can you please confirm

**Comment by Totonyus** [comment]
Hi.

I have absolutely no clue.

I'll maybe try later today if I find how. Do you have logs or error message ?

**Comment by vasanthtt** [comment]
![image](https://user-images.githubusercontent.com/724399/210377103-ced1dba8-eab1-4c58-bfbd-8d9e6df84f52.png)

In log
exec /bin/sh: exec format error

**Comment by Totonyus** [comment]
Two things :
- You are using ydl_api wich is deprecated
- I build the ydl_api_ng:preview image for arm64, can you try this one ?

**Comment by vasanthtt** [comment]
My bad! I referred your documentation which you need to correct the image name https://github.com/Totonyus/ydl_api_ng#by-command-line

**Comment by vasanthtt** [comment]
Was so happy when i deployed without any error. info API returned me as expected. But when I tried to download I get "internal server error" [logs here.](https://pastebin.com/Ecq04ceP)
![image](https://user-images.githubusercontent.com/724399/210481214-13fec285-5b1d-4d6a-a49d-6f4a28dd28ab.png)

**Comment by Totonyus** [comment]
> My bad! I referred your documentation which you need to correct the image name https://github.com/Totonyus/ydl_api_ng#by-command-line

Thank you for the warning. I'll correct.

The error message you have means the application can't connect to redis. 

You can refer to the docker-compose file : https://github.com/Totonyus/ydl_api_ng/blob/main/docker-compose.yml

If you don't want to use redis you can disable it in the params.ini file :
```
[app]
_enable_redis = false
```

And set the docker environment variable `DISABLE_REDIS=true`

However a few features rely on redis and won't be available (advanced queue management and programmation).

**Comment by vasanthtt** [comment]
after `_enable_redis = false` i still faced an error .. but when I up-compose file, it is super good now.  thanks a lot... wonderful work. Let me know when you push this to the normal version.

**Comment by vasanthtt** [comment]
let me know if i can close this issue

**Comment by Totonyus** [comment]
Commit 8b7027492559c9b0898cd6f055c8e9b5c6a7c7f1 pushed on main and images built in https://github.com/Totonyus/ydl_api_ng/actions/runs/3839035981.

Thank you for improving this application :)

(You can close is it's ok for you)
